spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/house
    username: postgres
    password: postgres

  jpa:
    hibernate:
      hbm2ddl:
        auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

